services:
  - type: web
    name: mercado-pago-transparent-checkout
    env: python
    plan: free
    autoDeploy: true
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --bind 0.0.0.0:$PORT --log-file -
    envVars:
      - key: MP_PUBLIC_KEY
      - key: MP_ACCESS_TOKEN
